config/routes.rb
Importer::Application.routes.draw do
  resources :inventory_withdrawals do
    get :autocomplete_bottling_display_name, :on => :collection
  end

  resources :bottlings

  resources :producers

  resources :wines

  root :to => 'wines#index'

end

app/models/bottling.rb
class Bottling < ActiveRecord::Base
  belongs_to :wine
  has_many :inventory_withdrawal_items
  
  SIZES = %w(375ml 500ml 750ml 1500ml 3000ml)
  
  validates :wine, :presence => true
  validates :bottle_size, :presence => true
  validates :sku, :uniqueness => true
  
  after_create :set_display_name
  after_update :set_display_name, :if => lambda { bottle_size_changed? }

  def set_display_name
    update_column :display_name, full_name
  end

  def full_name
    "#{wine.display_vintage} #{wine.producer.name} #{wine.name} | #{bottle_size}"
  end 
  
  def quantity_on_hand
    100 - InventoryWithdrawalItem.sum(:quantity, :conditions => { :bottling_id => self.id })
    # - LineItem.where(:wine_id => self.id, self.order => "closed").sum("quantity")
  end
  
  def quantity_reserved
    5   # LineItem.where(self.order => "open").sum("quantity")
  end
  
  def quantity_available
    self.quantity_on_hand.to_i - self.quantity_reserved.to_i
  end   
end

app/controllers/bottlings_controller.rb
class BottlingsController < ApplicationController
  include ApplicationHelper

  # GET /bottlings
  # GET /bottlings.json
  def index
    @bottlings = handle_sorting(:bottling, :sku, :wine, :bottle_size)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @bottlings }
    end
  end

  # GET /bottlings/1
  # GET /bottlings/1.json
  def show
    @bottling = Bottling.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @bottling }
    end
  end

  # GET /bottlings/new
  # GET /bottlings/new.json
  def new
    @bottling = Bottling.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @bottling }
    end
  end

  # GET /bottlings/1/edit
  def edit
    @bottling = Bottling.find(params[:id])
  end

  # POST /bottlings
  # POST /bottlings.json
  def create
    @bottling = Bottling.new(params[:bottling])

    respond_to do |format|
      if @bottling.save
        format.html { redirect_to @bottling, notice: 'bottling was successfully created.' }
        format.json { render json: @bottling, status: :created, location: @bottling }
      else
        format.html { render action: "new" }
        format.json { render json: @bottling.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /bottlings/1
  # PUT /bottlings/1.json
  def update
    @bottling = Bottling.find(params[:id])

    respond_to do |format|
      if @bottling.update_attributes(params[:bottling])
        format.html { redirect_to @bottling, notice: 'bottling was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @bottling.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bottlings/1
  # DELETE /bottlings/1.json
  def destroy
    @bottling = Bottling.find(params[:id])
    @bottling.destroy

    respond_to do |format|
      format.html { redirect_to bottlings_url }
      format.json { head :ok }
    end
  end
end

app/helpers/bottlings_helper.rb
module BottlingsHelper
end

app/views/bottlings/_form.html.haml
= form_for @bottling do |f|
  -if @bottling.errors.any?
    .alert.alert-error
      %h4= "#{pluralize(@bottling.errors.count, "error")} prohibited this bottling from being saved:"
      %ul
        - @bottling.errors.full_messages.each do |msg|
          %li= msg
  .field
    %label{ :for => "bottling_sku" } SKU
    = f.text_field :sku
  .field
    = f.label :wine
    = collection_select(:bottling, :wine_id, Wine.all, :id, :full_name)
  .field
    = f.label :bottle_size
    = select("bottling", "bottle_size", Bottling::SIZES)
  .field
    = f.label :warehouse_location
    = f.text_field :warehouse_location
  .actions
    = save_button

app/views/bottlings/_inventory_table.html.haml
%table.table.table-striped.table-condensed
  %tr
    %th On Hand
    %th Reserved
    %th Available
  - bottlings.each do |b|
    %tr{ :class => "sku" }
      %th{ :colspan => 3 }= "#{b.bottle_size} - #{b.sku}"
    %tr
      %td= b.quantity_on_hand
      %td= b.quantity_reserved
      %td= b.quantity_available

app/views/bottlings/edit.html.haml
%h1 Editing bottling

= render 'form'

= link_to 'View', @bottling
\|
= link_to 'Back', bottlings_path

app/views/bottlings/index.html.haml
%h1 Bottlings

= link_to 'New Bottling', new_bottling_path
%br
%br

.row
  %table.table.table-condensed.table-striped.span9
    %tr
      %th= sort_link("SKU", :sku)
      %th Wine
      %th= sort_link("Bottle size", :bottle_size)
      %th Warehouse location
      %th.span2

    - @bottlings.each do |bottling|
      %tr
        %td= bottling.sku
        %td= bottling.wine.name
        %td= bottling.bottle_size
        %td= bottling.warehouse_location
        %td
          = link_to 'View', bottling
          \/
          = link_to 'Edit', edit_bottling_path(bottling)
          \/
          = link_to 'Delete', bottling, :confirm => 'Are you sure?', :method => :delete
  = will_paginate @bottlings

app/views/bottlings/new.html.haml
%h1 New Bottling
= render 'form'
= back_link(bottlings_path)

app/views/bottlings/show.html.haml
%p#notice= notice

%p
  %b Wine:
  = @bottling.wine.name
%p
  %b Bottle size:
  = @bottling.bottle_size
%p
  %b Warehouse location:
  = @bottling.warehouse_location

%h3 Inventory
.inventory
  = render :partial => "bottlings/inventory_table", :locals => { :bottlings => [@bottling] }

= link_to 'Edit', edit_bottling_path(@bottling)
\|
= link_to 'Back', bottlings_path