config/routes.rb
Importer::Application.routes.draw do
  resources :inventory_withdrawals do
    get :autocomplete_bottling_display_name, :on => :collection
  end

  resources :bottlings

  resources :producers

  resources :wines

  root :to => 'wines#index'

end

app/models/inventory_withdrawal.rb
class InventoryWithdrawal < ActiveRecord::Base
  has_many :inventory_withdrawal_items, :dependent => :destroy
  accepts_nested_attributes_for :inventory_withdrawal_items, :allow_destroy => true
  # validates_associated :inventory_withdrawal_items
  
  validates :date, :category, :presence => { :message => " must be specified."}

  validate do |inventory_withdrawal|
    inventory_withdrawal.errors[:base] << "You must add at least one item." if inventory_withdrawal.inventory_withdrawal_items.empty?
  end  

  TYPES = %w(tasting corked broken personal)
end

app/controllers/inventory_withdrawals_controller.rb
class InventoryWithdrawalsController < ApplicationController
  include ApplicationHelper

  autocomplete :bottling, :display_name, :full => true

  # GET /inventory_withdrawals
  # GET /inventory_withdrawals.json
  def index
    @inventory_withdrawals = handle_sorting(:inventory_withdrawal, :date, :category)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @inventory_withdrawals }
    end
  end

  # GET /inventory_withdrawals/1
  # GET /inventory_withdrawals/1.json
  def show
    @inventory_withdrawal = InventoryWithdrawal.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @inventory_withdrawal }
    end
  end

  # GET /inventory_withdrawals/new
  # GET /inventory_withdrawals/new.json
  def new
    @inventory_withdrawal = InventoryWithdrawal.new
    @inventory_withdrawal.inventory_withdrawal_items.build

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @inventory_withdrawal }
    end
  end

  # GET /inventory_withdrawals/1/edit
  def edit
    @inventory_withdrawal = InventoryWithdrawal.find(params[:id])
  end

  # POST /inventory_withdrawals
  # POST /inventory_withdrawals.json
  def create
    @inventory_withdrawal = InventoryWithdrawal.new(params[:inventory_withdrawal])

    respond_to do |format|
      if @inventory_withdrawal.save
        format.html { redirect_to @inventory_withdrawal, notice: 'Inventory withdrawal was successfully created.' }
        format.json { render json: @inventory_withdrawal, status: :created, location: @inventory_withdrawal }
      else
        format.html { render action: "new" }
        format.json { render json: @inventory_withdrawal.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /inventory_withdrawals/1
  # PUT /inventory_withdrawals/1.json
  def update
    @inventory_withdrawal = InventoryWithdrawal.find(params[:id])

    respond_to do |format|
      if @inventory_withdrawal.update_attributes(params[:inventory_withdrawal])
        format.html { redirect_to @inventory_withdrawal, notice: 'Inventory withdrawal was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @inventory_withdrawal.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /inventory_withdrawals/1
  # DELETE /inventory_withdrawals/1.json
  def destroy
    @inventory_withdrawal = InventoryWithdrawal.find(params[:id])
    @inventory_withdrawal.destroy

    respond_to do |format|
      format.html { redirect_to inventory_withdrawals_url }
      format.json { head :ok }
    end
  end
end

app/helpers/inventory_withdrawals_helper.rb
module InventoryWithdrawalsHelper
end

app/views/inventory_withdrawals/_form.html.haml
= simple_nested_form_for(@inventory_withdrawal, :html => {:class => 'form-vertical' }) do |f|
  -if @inventory_withdrawal.errors.any?
    .alert.alert-error
      %h4= "#{pluralize(@inventory_withdrawal.errors.count, "error")} prohibited this inventory_withdrawal from being saved:"
      %ul
        - @inventory_withdrawal.errors.full_messages.each do |msg|
          %li= msg

  = f.input :date, :as => :date, :input_html => { :class => "input-small" }
  = f.input :category, :collection => InventoryWithdrawal::TYPES, :prompt => "select...", :input_html => { :class => "input-small" }
  = f.input :notes, :as => :text, :input_html => { :rows => 2 }

  .actions
    = f.link_to_add '<i class="icon-plus icon-white"></i> Add Item'.html_safe, :inventory_withdrawal_items, :class => "btn btn-primary"
    = save_button

  .above_new_items
  = f.simple_fields_for :inventory_withdrawal_items

app/views/inventory_withdrawals/_inventory_withdrawal_item_fields.html.haml
- unique_id = Digest::SHA1.hexdigest([Time.now, rand].join)
.row.item
  = f.input :dummy,
            :label => false, 
            :url => autocomplete_bottling_display_name_inventory_withdrawals_path, 
            :as => :autocomplete,
            :input_html => { :class => "span5" , :value => f.object.try(:bottling).try(:display_name) },
            :id_element => "input##{unique_id}"
  = f.input :bottling_id, :as => :hidden, :input_html => { :id => unique_id }
  = f.input :quantity, :label => false, :placeholder => "Quantity", :input_html => { :class => "input-small" }
  = f.link_to_remove '<i class="icon-minus icon-white"></i>'.html_safe, :class => "btn btn-danger"

app/views/inventory_withdrawals/edit.html.haml
= javascript_include_tag "inventory_withdrawals"

%h1 Editing Inventory Withdrawal

= render 'form'

= link_to 'View', @inventory_withdrawal
\|
= link_to 'Back', inventory_withdrawals_path

app/views/inventory_withdrawals/index.html.haml
%h1 Inventory Withdrawals
= link_to 'New Withdrawal', new_inventory_withdrawal_path
%br
%br
.row
  %table.table.table-condensed.table-striped.span4
    %tr
      %th= sort_link("Date", :date)
      %th= sort_link("Category", :category)
      %th.span2

    - @inventory_withdrawals.each do |inventory_withdrawal|
      %tr
        %td= inventory_withdrawal.date
        %td= inventory_withdrawal.category
        %td
          = link_to 'View', inventory_withdrawal
          \/
          = link_to 'Edit', edit_inventory_withdrawal_path(inventory_withdrawal)
          \/
          = link_to 'Delete', inventory_withdrawal, :confirm => 'Are you sure?', :method => :delete
= will_paginate @inventory_withdrawals      

app/views/inventory_withdrawals/new.html.haml
= javascript_include_tag "inventory_withdrawals"

%h1 New Inventory Withdrawal
= back_link(inventory_withdrawals_path)
= render 'form'

app/views/inventory_withdrawals/show.html.haml
%p#notice= notice

%p
  %b Date:
  = @inventory_withdrawal.date
%p
  %b Category:
  = @inventory_withdrawal.category
%p
  %b Notes:
  = @inventory_withdrawal.notes

%table
  %tr
    %th Quantity
    %th Wine
    %th Bottle

  - @inventory_withdrawal.inventory_withdrawal_items.each do |inventory_withdrawal_item|
    - puts inventory_withdrawal_item.inspect
    %tr
      %td= inventory_withdrawal_item.quantity
      %td= inventory_withdrawal_item.bottling.wine.name
      %td= inventory_withdrawal_item.bottling.bottle_size
%br        
= link_to 'Edit', edit_inventory_withdrawal_path(@inventory_withdrawal)
\|
= link_to 'Back', inventory_withdrawals_path