config/routes.rb
Importer::Application.routes.draw do
  resources :inventory_withdrawals do
    get :autocomplete_bottling_display_name, :on => :collection
  end

  resources :bottlings

  resources :producers

  resources :wines

  root :to => 'wines#index'

end

app/models/producer.rb
class Producer < ActiveRecord::Base
  has_many :wines
  
  validates :name, :email, :presence => true
end

app/controllers/producers_controller.rb
class ProducersController < ApplicationController
  include ApplicationHelper
  
  # GET /producers
  # GET /producers.json
  def index
    @producers = handle_sorting(:producer, :name)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @producers }
    end
  end

  # GET /producers/1
  # GET /producers/1.json
  def show
    @producer = Producer.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @producer }
    end
  end

  # GET /producers/new
  # GET /producers/new.json
  def new
    @producer = Producer.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @producer }
    end
  end

  # GET /producers/1/edit
  def edit
    @producer = Producer.find(params[:id])
  end

  # POST /producers
  # POST /producers.json
  def create
    @producer = Producer.new(params[:producer])

    respond_to do |format|
      if @producer.save
        format.html { redirect_to @producer, notice: 'Producer was successfully created.' }
        format.json { render json: @producer, status: :created, location: @producer }
      else
        format.html { render action: "new" }
        format.json { render json: @producer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /producers/1
  # PUT /producers/1.json
  def update
    @producer = Producer.find(params[:id])

    respond_to do |format|
      if @producer.update_attributes(params[:producer])
        format.html { redirect_to @producer, notice: 'Producer was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @producer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /producers/1
  # DELETE /producers/1.json
  def destroy
    @producer = Producer.find(params[:id])
    @producer.destroy

    respond_to do |format|
      format.html { redirect_to producers_url }
      format.json { head :ok }
    end
  end
end

app/helpers/producers_helper.rb
module ProducersHelper
end

app/views/producers/_form.html.haml
= form_for @producer do |f|
  -if @producer.errors.any?
    .alert.alert-error
      %h4= "#{pluralize(@producer.errors.count, "error")} prohibited this producer from being saved:"
      %ul
        - @producer.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :email
    = f.text_field :email
  .field
    = f.label :phone
    = f.text_field :phone
  .field
    = f.label :address
    = f.text_field :address
  .field
    = f.label :notes
    = f.text_area :notes, :rows => 4
  .actions
    = save_button

app/views/producers/edit.html.haml
%h1 Editing producer

= render 'form'

= link_to 'View', @producer
\|
= link_to 'Back', producers_path

app/views/producers/index.html.haml
%h1 Producers

= link_to 'New Producer', new_producer_path
%br
%br

.row
  %table.table.table-condensed.table-striped.span10
    %tr
      %th Name
      %th Email
      %th Phone
      %th Address
      %th.span2

    - @producers.each do |producer|
      %tr
        %td= producer.name
        %td= producer.email
        %td= producer.phone
        %td= producer.address
        %td
          = link_to 'View', producer
          \/
          = link_to 'Edit', edit_producer_path(producer)
          \/
          = link_to 'Delete', producer, :confirm => 'Are you sure?', :method => :delete
  = will_paginate @producers

app/views/producers/new.html.haml
%h1 New Producer
= render 'form'
= back_link(producers_path)

app/views/producers/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @producer.name
%p
  %b Email:
  = @producer.email
%p
  %b Phone:
  = @producer.phone
%p
  %b Address:
  = @producer.address
%p
  %b Notes:
  = @producer.notes

= link_to 'Edit', edit_producer_path(@producer)
\|
= link_to 'Back', producers_path