config/routes.rb
Importer::Application.routes.draw do
  resources :inventory_withdrawals do
    get :autocomplete_bottling_display_name, :on => :collection
  end

  resources :bottlings

  resources :producers

  resources :wines

  root :to => 'wines#index'

end

app/views/layouts/_messages.html.haml
- flash.each do |name, msg|
  %div{:class => "alert alert-#{name == :notice ? "success" : "error"}"}
    %a.close{"data-dismiss" => "alert"} ×
    = content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String)

app/views/layouts/_navigation.html.haml
%a.btn.btn-navbar{ :data => { :toggle => "collapse", :target => ".nav-collapse" } }
  %span.icon-bar
  %span.icon-bar
  %span.icon-bar
  %span.icon-bar

= link_to "Importer", root_path, :class => 'brand'
.nav-collapse
  %ul.nav
    %li
      = link_to("Bottlings", bottlings_path)
    %li
      = link_to("Wines", wines_path)
    %li
      = link_to("Producers", producers_path)
    %li
      = link_to("Withdrawals", inventory_withdrawals_path)

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:charset => "utf-8"}
    %meta{"http-equiv" => "X-UA-Compatible", :content => "IE=edge,chrome=1"}
    %meta{:name => "viewport", :content => "width=device-width, initial-scale=1, maximum-scale=1"}
    %title= content_for?(:title) ? yield(:title) : Importer
    %meta{:content => "", :name => "description"}
    %meta{:content => "", :name => "author"}    
    = stylesheet_link_tag "application", :media => "all"
    = javascript_include_tag "application"
    = csrf_meta_tags
    = yield(:head)
  %body{:class => params[:controller]}
    %header.navbar.navbar-fixed-top
      %nav.navbar-inner
        .container
          = render 'layouts/navigation'
    #main{:role => "main"}
      .container
        .content
          .row
            .span12
              = render 'layouts/messages'
              = yield
          %footer